--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-04-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPEAKROOM
--------------------------------------------------------

  CREATE TABLE "SKOTT"."SPEAKROOM" 
   (	"ROOMID" NUMBER(10,0), 
	"SPEAKMEMBER1" VARCHAR2(20 BYTE), 
	"SPEAKMEMBER2" VARCHAR2(20 BYTE), 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.SPEAKROOM
SET DEFINE OFF;
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (4,'희영','영수',to_timestamp('23/08/03 18:26:42.574241000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (6,'영수','희영',to_timestamp('23/08/03 18:30:21.193363000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (9,'희영','영수',to_timestamp('23/08/03 18:32:53.009245000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (11,'희영','영수',to_timestamp('23/08/03 18:35:38.517236000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (130,'희영','영수',to_timestamp('23/08/03 18:37:24.054854000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (2,'희영','영수',to_timestamp('23/08/03 15:10:41.571084000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (5,'희영','영수',to_timestamp('23/08/03 18:25:23.514785000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (7,'희영','영수',to_timestamp('23/08/04 15:39:00.807587000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (8,'희영','영수',to_timestamp('23/08/04 15:41:21.625401000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (12,'희영','영수',to_timestamp('23/08/04 17:08:57.232726000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (10,'희영','영수',to_timestamp('23/08/04 17:09:59.949655000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (13,'희영','영수',to_timestamp('23/08/04 17:11:44.465064000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.SPEAKROOM (ROOMID,SPEAKMEMBER1,SPEAKMEMBER2,CREATED_TIME) values (15,'희영','영수',to_timestamp('23/08/04 17:15:29.891064000','RR/MM/DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index SPEAKROOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."SPEAKROOM_PK" ON "SKOTT"."SPEAKROOM" ("ROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SPEAKROOM_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."SPEAKROOM_TRG" 
BEFORE INSERT ON SPEAKROOM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."SPEAKROOM_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPEAKROOM
--------------------------------------------------------

  ALTER TABLE "SKOTT"."SPEAKROOM" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."SPEAKROOM" ADD CONSTRAINT "SPEAKROOM_PK" PRIMARY KEY ("ROOMID")
  USING INDEX "SKOTT"."SPEAKROOM_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPEAKROOM
--------------------------------------------------------

  ALTER TABLE "SKOTT"."SPEAKROOM" ADD CONSTRAINT "FK_SPEAKMEMBER1" FOREIGN KEY ("SPEAKMEMBER1")
	  REFERENCES "SKOTT"."USERINFO" ("ID") ENABLE;
  ALTER TABLE "SKOTT"."SPEAKROOM" ADD CONSTRAINT "FK_SPEAKMEMBER2" FOREIGN KEY ("SPEAKMEMBER2")
	  REFERENCES "SKOTT"."USERINFO" ("ID") ENABLE;
