--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-04-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPEAKCHAT
--------------------------------------------------------

  CREATE TABLE "SKOTT"."SPEAKCHAT" 
   (	"ID" NUMBER(10,0), 
	"CHATFILE" VARCHAR2(2000 CHAR), 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"REPORT" NUMBER(10,0), 
	"ROOMID" NUMBER(10,0), 
	"REPORTER" VARCHAR2(40 BYTE), 
	"RESPONDENT" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.SPEAKCHAT
SET DEFINE OFF;
Insert into SKOTT.SPEAKCHAT (ID,CHATFILE,CREATED_TIME,REPORT,ROOMID,REPORTER,RESPONDENT) values (13,null,to_timestamp('23/08/04 14:21:30.748848000','RR/MM/DD HH24:MI:SSXFF'),1,5,'희영','영구');
Insert into SKOTT.SPEAKCHAT (ID,CHATFILE,CREATED_TIME,REPORT,ROOMID,REPORTER,RESPONDENT) values (17,null,to_timestamp('23/08/04 17:16:36.191787000','RR/MM/DD HH24:MI:SSXFF'),1,15,'희영','영구');
Insert into SKOTT.SPEAKCHAT (ID,CHATFILE,CREATED_TIME,REPORT,ROOMID,REPORTER,RESPONDENT) values (15,null,to_timestamp('23/08/04 15:39:45.313519000','RR/MM/DD HH24:MI:SSXFF'),1,7,'희영','영구');
Insert into SKOTT.SPEAKCHAT (ID,CHATFILE,CREATED_TIME,REPORT,ROOMID,REPORTER,RESPONDENT) values (16,null,to_timestamp('23/08/04 15:42:44.460400000','RR/MM/DD HH24:MI:SSXFF'),1,8,'희영','영구');
Insert into SKOTT.SPEAKCHAT (ID,CHATFILE,CREATED_TIME,REPORT,ROOMID,REPORTER,RESPONDENT) values (14,null,to_timestamp('23/08/04 15:32:27.068675000','RR/MM/DD HH24:MI:SSXFF'),1,6,'희영','영구');
--------------------------------------------------------
--  DDL for Index SPEAKCHAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."SPEAKCHAT_PK" ON "SKOTT"."SPEAKCHAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SPEAKCHAT_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."SPEAKCHAT_TRG" 
BEFORE INSERT ON SPEAKCHAT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."SPEAKCHAT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPEAKCHAT
--------------------------------------------------------

  ALTER TABLE "SKOTT"."SPEAKCHAT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."SPEAKCHAT" ADD CONSTRAINT "SPEAKCHAT_PK" PRIMARY KEY ("ID")
  USING INDEX "SKOTT"."SPEAKCHAT_PK"  ENABLE;
  ALTER TABLE "SKOTT"."SPEAKCHAT" ADD CONSTRAINT "SC_REPORT_CK" CHECK (REPORT BETWEEN 0 AND 1000) ENABLE;
  ALTER TABLE "SKOTT"."SPEAKCHAT" MODIFY ("REPORTER" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."SPEAKCHAT" MODIFY ("RESPONDENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SPEAKCHAT
--------------------------------------------------------

  ALTER TABLE "SKOTT"."SPEAKCHAT" ADD CONSTRAINT "FK_ROOMID" FOREIGN KEY ("ROOMID")
	  REFERENCES "SKOTT"."SPEAKROOM" ("ROOMID") ENABLE;
