--------------------------------------------------------
--  파일이 생성됨 - 금요일-8월-04-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERINFO
--------------------------------------------------------

  CREATE TABLE "SKOTT"."USERINFO" 
   (	"ID" VARCHAR2(40 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"SEX" NUMBER, 
	"ROLE" NUMBER, 
	"PHONE" VARCHAR2(40 BYTE), 
	"NICKNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 CHAR), 
	"BIRTHDAY" DATE DEFAULT systimestamp, 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"MODIFIED_TIME" TIMESTAMP (6) DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.USERINFO
SET DEFINE OFF;
Insert into SKOTT.USERINFO (ID,NAME,PASSWORD,EMAIL,SEX,ROLE,PHONE,NICKNAME,ADDRESS,BIRTHDAY,CREATED_TIME,MODIFIED_TIME) values ('영수','영구','123455555','ee',1,1,'010-1234-5678','강남멋쟁이','2',to_date('2023/08/02 11:43:41','YYYY/MM/DD HH24:MI:SS'),to_timestamp('23/08/02 11:43:51.236164000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/02 11:43:53.300039000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.USERINFO (ID,NAME,PASSWORD,EMAIL,SEX,ROLE,PHONE,NICKNAME,ADDRESS,BIRTHDAY,CREATED_TIME,MODIFIED_TIME) values ('희영','희영','123455555','ee',2,1,'010-1234-5678','강남멋쟁이','2',to_date('2023/08/02 11:43:41','YYYY/MM/DD HH24:MI:SS'),to_timestamp('23/08/02 11:43:51.236164000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/02 11:43:53.300039000','RR/MM/DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index USERINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."USERINFO_PK" ON "SKOTT"."USERINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger USERINFO_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."USERINFO_TRG" 
BEFORE INSERT ON USERINFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."USERINFO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table USERINFO
--------------------------------------------------------

  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" ADD CONSTRAINT "UI_ROLE_CK" CHECK (ROLE BETWEEN 0 AND 10) ENABLE;
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."USERINFO" ADD CONSTRAINT "USERINFO_PK" PRIMARY KEY ("ID")
  USING INDEX "SKOTT"."USERINFO_PK"  ENABLE;
