--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEETINGMEMBER
--------------------------------------------------------

  CREATE TABLE "SKOTT"."MEETINGMEMBER" 
   (	"ID" NUMBER(10,0), 
	"MEETID" NUMBER(10,0), 
	"USERID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.MEETINGMEMBER
SET DEFINE OFF;
Insert into SKOTT.MEETINGMEMBER (ID,MEETID,USERID) values (-1,-1,'희영');
Insert into SKOTT.MEETINGMEMBER (ID,MEETID,USERID) values (-2,-2,'희영');
--------------------------------------------------------
--  DDL for Index MEETINGMEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."MEETINGMEMBER_PK" ON "SKOTT"."MEETINGMEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger MEETINGMEMBER_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."MEETINGMEMBER_TRG" 
BEFORE INSERT ON MEETINGMEMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."MEETINGMEMBER_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MEETINGMEMBER
--------------------------------------------------------

  ALTER TABLE "SKOTT"."MEETINGMEMBER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETINGMEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETINGMEMBER" ADD CONSTRAINT "MEETINGMEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEETINGMEMBER
--------------------------------------------------------

  ALTER TABLE "SKOTT"."MEETINGMEMBER" ADD CONSTRAINT "MEETINGMEMBER_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "SKOTT"."PROFILE" ("USER_ID") ENABLE;
  ALTER TABLE "SKOTT"."MEETINGMEMBER" ADD CONSTRAINT "MEETINGMEMBER_FK1" FOREIGN KEY ("MEETID")
	  REFERENCES "SKOTT"."MEETING" ("ID") ENABLE;
