--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "SKOTT"."LOCATION" 
   (	"ID" NUMBER(10,0), 
	"LOCATIONNAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.LOCATION
SET DEFINE OFF;
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (1,'서울 남부( 강남, 관악, 송파 등 )');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (2,'서울 북부( 마포, 종로, 중랑 등 )');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (3,'경기 북부( 의정부, 파주, 양주 등 )');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (4,'경기 남부 ( 수원, 용인, 성남 등 )');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (5,'충청북도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (6,'충청남도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (7,'경상북도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (8,'경상남도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (9,'강원도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (10,'전라북도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (11,'전라남도');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (12,'인천');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (13,'대전');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (14,'대구');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (15,'울산');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (16,'부산');
Insert into SKOTT.LOCATION (ID,LOCATIONNAME) values (17,'광주');
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."LOCATION_PK" ON "SKOTT"."LOCATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger LOCATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."LOCATION_TRG" 
BEFORE INSERT ON LOCATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LOCATION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."LOCATION_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "SKOTT"."LOCATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."LOCATION" MODIFY ("LOCATIONNAME" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
