--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEETING
--------------------------------------------------------

  CREATE TABLE "SKOTT"."MEETING" 
   (	"ID" NUMBER(10,0), 
	"LEADER" VARCHAR2(40 BYTE), 
	"MEMBER" NUMBER(2,0) DEFAULT 0, 
	"STATUS" NUMBER(1,0) DEFAULT 0, 
	"HOBBY" NUMBER(3,0) DEFAULT 0, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT1" VARCHAR2(500 BYTE) DEFAULT '.', 
	"CONTENT2" VARCHAR2(500 BYTE) DEFAULT '.', 
	"CONTENT3" VARCHAR2(500 BYTE) DEFAULT '.', 
	"IMAGE1" VARCHAR2(3000 BYTE), 
	"IMAGE2" VARCHAR2(3000 BYTE), 
	"IMAGE3" VARCHAR2(3000 BYTE), 
	"CONTENTS" VARCHAR2(1000 BYTE), 
	"LOCATION" NUMBER(2,0) DEFAULT 0, 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"MODIFIED_TIME" TIMESTAMP (6) DEFAULT systimestamp, 
	"MEETINGDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.MEETING
SET DEFINE OFF;
Insert into SKOTT.MEETING (ID,LEADER,MEMBER,STATUS,HOBBY,TITLE,CONTENT1,CONTENT2,CONTENT3,IMAGE1,IMAGE2,IMAGE3,CONTENTS,LOCATION,CREATED_TIME,MODIFIED_TIME,MEETINGDATE) values (-1,'희영',1,0,101,'축구 할 사람','안녕','소개','이야','C:/IMA/defaultimg.jpg','C:/IMA/defaultimg.jpg','C:/IMA/defaultimg.jpg','본문 내용입니다',2,to_timestamp('23/08/09 13:52:45.130000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/09 13:52:38.389569000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/09 13:52:41.835066000','RR/MM/DD HH24:MI:SSXFF'));
Insert into SKOTT.MEETING (ID,LEADER,MEMBER,STATUS,HOBBY,TITLE,CONTENT1,CONTENT2,CONTENT3,IMAGE1,IMAGE2,IMAGE3,CONTENTS,LOCATION,CREATED_TIME,MODIFIED_TIME,MEETINGDATE) values (-2,'희영',1,0,101,'운동 할 사람','안녕','소개','이야','C:/IMA/defaultimg.jpg','C:/IMA/defaultimg.jpg','C:/IMA/defaultimg.jpg','본문 내용입니다',2,to_timestamp('23/08/09 13:52:45.130000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/09 13:52:38.389569000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('23/08/09 13:52:41.835066000','RR/MM/DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index MEETING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."MEETING_PK" ON "SKOTT"."MEETING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger MEETING_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."MEETING_TRG" 
BEFORE INSERT ON MEETING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."MEETING_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MEETING
--------------------------------------------------------

  ALTER TABLE "SKOTT"."MEETING" MODIFY ("LEADER" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETING" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETING" MODIFY ("CONTENTS" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETING" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETING" ADD CONSTRAINT "MEETING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SKOTT"."MEETING" MODIFY ("IMAGE1" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."MEETING" MODIFY ("LOCATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MEETING
--------------------------------------------------------

  ALTER TABLE "SKOTT"."MEETING" ADD CONSTRAINT "MEETING_FK1" FOREIGN KEY ("HOBBY")
	  REFERENCES "SKOTT"."HOBBY" ("HOBBY_ID") ENABLE;
  ALTER TABLE "SKOTT"."MEETING" ADD CONSTRAINT "MEETING_FK2" FOREIGN KEY ("LOCATION")
	  REFERENCES "SKOTT"."LOCATION" ("ID") ENABLE;
