--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANNOUNCEMENT_EVENT
--------------------------------------------------------

  CREATE TABLE "SKOTT"."ANNOUNCEMENT_EVENT" 
   (	"ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(100 CHAR), 
	"AUTHOR" VARCHAR2(20 CHAR), 
	"CONTENT" VARCHAR2(400 CHAR), 
	"CREATED_TIME" TIMESTAMP (6) DEFAULT sysdate, 
	"MODIFIED_TIME" TIMESTAMP (6) DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.ANNOUNCEMENT_EVENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ANNOUNCEMENT_EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."ANNOUNCEMENT_EVENT_PK" ON "SKOTT"."ANNOUNCEMENT_EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ANNOUNCEMENT_EVENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."ANNOUNCEMENT_EVENT_TRG" 
BEFORE INSERT ON ANNOUNCEMENT_EVENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ANNOUNCEMENT_EVENT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOTT"."ANNOUNCEMENT_EVENT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ANNOUNCEMENT_EVENT
--------------------------------------------------------

  ALTER TABLE "SKOTT"."ANNOUNCEMENT_EVENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."ANNOUNCEMENT_EVENT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."ANNOUNCEMENT_EVENT" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."ANNOUNCEMENT_EVENT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."ANNOUNCEMENT_EVENT" ADD CONSTRAINT "ANNOUNCEMENT_EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
