--------------------------------------------------------
--  파일이 생성됨 - 금요일-7월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "SKOTT"."PROFILE" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_AGE" NUMBER, 
	"USER_PERSONALITY" VARCHAR2(20 BYTE), 
	"USER_DRINKS" VARCHAR2(20 BYTE), 
	"USER_SMOKER" VARCHAR2(20 BYTE), 
	"USER_HEIGHT" VARCHAR2(20 BYTE), 
	"USER_ACADEMIC" NUMBER(10,0), 
	"USER_INCOME" NUMBER(10,0), 
	"USER_JOB" NUMBER(10,0), 
	"USER_RELIGION" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SKOTT.PROFILE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOTT"."PROFILE_PK" ON "SKOTT"."PROFILE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PROFILE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SKOTT"."PROFILE_TRG" 
BEFORE INSERT ON PROFILE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "SKOTT"."PROFILE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "SKOTT"."PROFILE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."PROFILE" MODIFY ("USER_PERSONALITY" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."PROFILE" MODIFY ("USER_DRINKS" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."PROFILE" MODIFY ("USER_SMOKER" NOT NULL ENABLE);
  ALTER TABLE "SKOTT"."PROFILE" ADD CONSTRAINT "PROFILE_PK" PRIMARY KEY ("USER_ID")
  USING INDEX "SKOTT"."PROFILE_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "SKOTT"."PROFILE" ADD CONSTRAINT "FK1_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "SKOTT"."USERINFO" ("ID") ENABLE;
  ALTER TABLE "SKOTT"."PROFILE" ADD CONSTRAINT "FK_ACADEMICID" FOREIGN KEY ("USER_ACADEMIC")
	  REFERENCES "SKOTT"."ACADEMIC" ("ACADEMIC_ID") ENABLE;
  ALTER TABLE "SKOTT"."PROFILE" ADD CONSTRAINT "FK_USERINCOME" FOREIGN KEY ("USER_INCOME")
	  REFERENCES "SKOTT"."INCOME" ("INCOME_ID") ENABLE;
  ALTER TABLE "SKOTT"."PROFILE" ADD CONSTRAINT "FK_USERJOB" FOREIGN KEY ("USER_JOB")
	  REFERENCES "SKOTT"."JOB" ("JOB_ID") ENABLE;
  ALTER TABLE "SKOTT"."PROFILE" ADD CONSTRAINT "FK_USERRELIGION" FOREIGN KEY ("USER_RELIGION")
	  REFERENCES "SKOTT"."RELIGION" ("RELIGION_ID") ENABLE;
